### ISSUE TITLE
Issue with external source time function -- Long simulation blows up after 50 steps.

### ISSUE THREAD

**Issue by lsawade** [SPECFEM/specfem3d_globe#806]
I have been heavily using the **external source time function** feature recently, and encounter a very strange phenomenon, for which I do not know where to start debugging.

## The Issue

The error that is thrown is 

```
Error: simulation became unstable in solid, process           1
      norm solid =          Infinity
 Please check time step setting in get_timestep_and_layers.f90, exiting...
 forward simulation became unstable in solid and blew up
 Error detected, aborting MPI... proc            1
```

However, I just use a very basic compilation with `1D_isotropic_PREM` and the error is only thrown after the first few timesteps `iff` the simulation time is longer than approximately 215 min. For the durations below the code runs without a problem. 

## What am I doing:

I used the most recent commit in `SPECFEM/specfem3d_globe -- devel` [f448e49](https://github.com/SPECFEM/specfem3d_globe/commit/f448e49fb2e385ebda28356a1d3c702a3610c56f) and changed only a few things; all contained in the attached zip below.

After meshing `values_from_mesher.h` indicates `0.18999998 s` as sampling interval which was used to create the `stf`

The problem, if architecture-independent, should be reproducible with the attached `DATA/stf` file, `DATA/Par_file`, `DATA/FORCESOLUTION`, and `setup/constants.h.in` file.

## Some other information

* The STF from `PRINT_SOURCE_TIME_FUNCTION` prints zeros only for the stf out to be.
* While the code runs for smaller lengths, it still slowly increases. not quite exploding.

My hope is that someone is going to tell me that I'm using the `stf` wrong.

## What I want: 

Run long specfem simulations with external STF without issues

[SF_ISSUE.zip](https://github.com/SPECFEM/specfem3d_globe/files/10069981/SF_ISSUE.zip)

**Comment by homnath** [comment]
Hi Lucas,
I am just curious, what is the problem, by the way?

Best,
Hom Nath
________________________________
From: Lucas Sawade ***@***.***>
Sent: Tuesday, November 22, 2022 1:18 PM
To: SPECFEM/specfem3d_globe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SPECFEM/specfem3d_globe] Issue with external source time function -- Long simulation blows up after 50 steps. (Issue #806)


I have been heavily using the external source time function feature recently, and encounter a very strange phenomenon, for which I do not know where to start debugging.

I used the most recent commit in specfem f448e49<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSPECFEM%2Fspecfem3d_globe%2Fcommit%2Ff448e49fb2e385ebda28356a1d3c702a3610c56f&data=05%7C01%7Chomnath.gharti%40queensu.ca%7C3986aba1f04b470da21508daccb5e655%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C638047381982771125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pX86EmFGrbC9DwtR1JWdnp4eipCEOrBcOU6dclgq31o%3D&reserved=0> and changed only a few things; all contained in the attached zip below.

The problem, if architecture-independent, should be reproducible with the attached DATA/stf file, DATA/Par_file, DATA/FORCESOLUTION, and setup/constants.h.in file.

One important point is that if the simulation time is reduced something smaller than 210 minutes, the code runs fine! Same stf, same code.

After meshing values_from_mesher.h indicates 0.18999998 s as sampling interval which was used to create the stf.

My hope here is that someone is going to tell me that I'm using the stf wrong.

SF_ISSUE.zip<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSPECFEM%2Fspecfem3d_globe%2Ffiles%2F10069981%2FSF_ISSUE.zip&data=05%7C01%7Chomnath.gharti%40queensu.ca%7C3986aba1f04b470da21508daccb5e655%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C638047381982771125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lcn2IXhV9iC%2BhRyk6o42MCShObAcojYtzYMWv4WfxZI%3D&reserved=0>

**Comment by lsawade** [comment]
> Hi Lucas, I am just curious, what is the problem, by the way? Best, Hom Nath
> […](#)

Hi Hom Nath, I elaborated a little in the original problem description.

**Comment by homnath** [comment]
Hi Lucas.
Unfortunately, I am not going to tell what you were hoping to hear:)
I ran your example with the version you're referring to on the tigercpu without any issues. If there is an issue, it may be GPU-related or platform-dependent?

Best,
Hom Nath

**Comment by lsawade** [comment]
Hi Hom Nath,

Good catch! It is related to the GPU compilation. It runs fine on the CPU... I'm not quite sure what's happening. I'll update here.

This is a new issue, maybe related to to some updates in the toolkit, or the compiler on traverse...

**Comment by lsawade** [comment]
## Problem found!

@danielpeter maybe interesting for you as well.

I have found the problem. And there is indeed an issue with how the external STF is read, or *rather* the way it seems to be able to read, for convenience I'll paste the routine below that is troublesome, it's located in [`comp_source_time_function.f90`](https://github.com/SPECFEM/specfem3d_globe/blob/devel/src/specfem3D/comp_source_time_function.f90) at the bottom.

<details>
<summary><code>get_EXTERNAL_SOURCE_TIME_FUNCTION()</code></summary>

```fortran
subroutine get_EXTERNAL_SOURCE_TIME_FUNCTION()

  use specfem_par, only: NSTEP, stfArray_external, IIN
  implicit none

  integer :: iterator,ier
  double precision :: temp
  character(len=256) :: line

  ! Allocate the source time function array to the number of time steps.
  allocate( stfArray_external(NSTEP),stat=ier)
  if (ier /= 0 ) stop 'Error allocating external source time function array'

  ! Read in source time function.
  open(unit=IIN, file='DATA/stf', status='old', form='formatted',iostat=ier)
  if (ier /= 0 ) stop 'Error opening file DATA/stf'

  read_loop: do iterator=1,NSTEP

    read(IIN, '(A)', iostat = ier) line
    if (ier /= 0) then
      print *, "Error in external source time function."
      stop 'Error reading external stf file'
    endif

    ! Ignore lines with a hash (comments)
    if (index(line, "#") /= 0) cycle read_loop

    read(line, *) temp
    write(*,*) 'STF', iterator, '/', NSTEP, 'val:', temp
    stfArray_external(iterator) = temp



  enddo read_loop

  close(IIN)

  end subroutine get_EXTERNAL_SOURCE_TIME_FUNCTION
```

</details>

For me, the issue was the cycle statement and the increasing iterator. When I started writing my code and implemented the external STF I saw this statement and thought, great! `cycle` probably keeps `iterator`, but reads the next line. But(!) `cycle` is Fortran's `continue` and therefore goes to the next iteration. Meaning that the header with seven comments will not be populate the array `stfArray_external(iterator)` properly because elements 1:7 are skipped.

@homnath I do not understand how this worked in the CPU version, but I assume it has to do with the values 1:7 that were not allocated correctly and how they were copied to the GPU. What baffles me is that I have been working with this type of STF for 4 months, and this happened now with every single type of  compilation I have tried. I must have been lucky/unlucky until now.

## Quick Fix

Remove any comments from the header of the STF, then `stfArray_external` is properly filled.

## Solution 

Fix read function using `while`, `counter` and skip if `#` in line method. Or, remove the `cycle` statement and talk about how to use an external STF in the docs.

**Comment by danielpeter** [comment]
thanks Lucas and Hom Nath! 

I updated that routine in PR #807 to allow again for comment lines in the DATA/stf file. please check if it still works for you, and let me know in case.

**Comment by lsawade** [comment]
Tested! No issues! Can be closed from where I stand!

Thanks @danielpeter!
